package com.sogeti.sun.demo.business


import java.util.List;

global Parameters parametres;

rule "Scenario Tilt Ombriere"
	ruleflow-group "Tilt"
	when 
		$scenario : Scenario( installationMode == InstallationMode.OMBRIERE && tilt == 0)
		
	then
		modify($scenario) {
			setTilt(40);
		}
	end

rule "Pas de latitude"
	ruleflow-group "Initial"
	when 
		$scenario : Scenario( latitude < 45)
	then
		modify($scenario) {
			setLatitude($scenario.getLatitude() + 5),
			setLongitude(5)
		}
	end

