package com.sogeti.sun.demo.business


import java.util.List;

global Parameters parametres;

rule "Scenario Ombriere"
	when 
		$scenario : Scenario( installationMode == InstallationMode.OMBRIERE && tilt == 0)
		
	then
		modify($scenario) {
			setTilt(40);
		}
	end

rule "Pas de latitude"
	when 
		$scenario : Scenario( latitude == 0)
	then
		modify($scenario) {
			setLatitude(45),
			setLongitude(5)
		}
	end

